server:
  port: 80
spring:
  thymeleaf:
    #    关闭模板缓冲 ctrl 加 f9 更新前端
    cache: false
  datasource:
    #    基本数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/adopt_cat?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
  mvc:
    #    设置静态资源路径
    static-path-pattern: /static/**
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  redis:
    port: 6379
    host: 121.196.150.46
    jedis:
      pool:
        max-idle: 8 #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1 # 连接池中的最大空闲连接
    lettuce:
      shutdown-timeout: 5000 # 连接超时时间（毫秒）
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

images:
    baseImagePath: E:/catData/
#  baseImagePath: /usr/adopt_cat/